### ISSUE TITLE
Fake issue. 

### ISSUE THREAD

**Issue by alecive** [ScazLab/HRC-model-set#1]
Ignore this.

**Comment by szeylikm** [comment]
![makerbotsettings](https://cloud.githubusercontent.com/assets/12373812/23683332/701683da-0366-11e7-8ba1-3ac8efa29b85.PNG)

**Comment by szeylikm** [comment]
![makerbotsettings20](https://cloud.githubusercontent.com/assets/12373812/23683341/7c1b8fb8-0366-11e7-82f6-870d0b399e3f.PNG)

**Comment by szeylikm** [comment]
![chairassemblylightfinal](https://cloud.githubusercontent.com/assets/12373812/23683588/d4976b34-0367-11e7-8ffe-7fc8ab9b6dd6.jpg)

**Comment by szeylikm** [comment]
![consoleassemblylightfinal](https://cloud.githubusercontent.com/assets/12373812/23683601/e2a5c1bc-0367-11e7-9647-fbce437b5b30.jpg)

**Comment by szeylikm** [comment]
![shelfassemblylightfinal](https://cloud.githubusercontent.com/assets/12373812/23683615/f7b5769c-0367-11e7-9f4d-f1979abac6a7.jpg)

**Comment by szeylikm** [comment]
![tableassemblylight](https://cloud.githubusercontent.com/assets/12373812/23683629/0b698e6c-0368-11e7-8cdd-c7b93e4e4a9a.jpg)

**Comment by szeylikm** [comment]
![img_2619](https://cloud.githubusercontent.com/assets/12373812/23770588/9837019c-04e1-11e7-904c-8a529ec3e6c5.JPG)

**Comment by szeylikm** [comment]
![img_2620](https://cloud.githubusercontent.com/assets/12373812/23770600/a79328a0-04e1-11e7-8bd3-d68dca7c0e5d.JPG)

**Comment by szeylikm** [comment]
![img_2623](https://cloud.githubusercontent.com/assets/12373812/23770608/afaff860-04e1-11e7-89b4-5f637e37c9e0.JPG)

**Comment by szeylikm** [comment]
![img_2666](https://cloud.githubusercontent.com/assets/12373812/23810630/5f09ac20-05a0-11e7-80ca-127fbf5938e9.JPG)

**Comment by szeylikm** [comment]
![img_2664](https://cloud.githubusercontent.com/assets/12373812/23810655/77331124-05a0-11e7-95b7-20e54b15aa75.JPG)

**Comment by sarah-widder** [comment]
![top180_2](https://cloud.githubusercontent.com/assets/19666316/24483871/ea9020bc-14c8-11e7-88a3-f2ac62ee6a3c.jpg)
![top180_1](https://cloud.githubusercontent.com/assets/19666316/24483869/ea8e33a6-14c8-11e7-8a1d-37396bb56151.jpg)
![top2](https://cloud.githubusercontent.com/assets/19666316/24483873/ea92b872-14c8-11e7-9062-95081aa2b107.jpg)
![top1](https://cloud.githubusercontent.com/assets/19666316/24483868/ea8d5436-14c8-11e7-8b05-e5e77b063ca4.jpg)
![shelf180_2](https://cloud.githubusercontent.com/assets/19666316/24483872/ea914906-14c8-11e7-9f47-ca3742c1927b.jpg)
![shelf180_1](https://cloud.githubusercontent.com/assets/19666316/24483870/ea8f6be0-14c8-11e7-941e-b023f96c4524.jpg)
![shelf90_3](https://cloud.githubusercontent.com/assets/19666316/24483877/ea99ae84-14c8-11e7-9118-923020e4606d.jpg)
![shelf90_2](https://cloud.githubusercontent.com/assets/19666316/24483874/ea962534-14c8-11e7-805b-c937265ebc11.jpg)
![shelf90_1](https://cloud.githubusercontent.com/assets/19666316/24483875/ea980d22-14c8-11e7-8498-171ba2791a18.jpg)
![foot2](https://cloud.githubusercontent.com/assets/19666316/24483879/ea9b14b8-14c8-11e7-9141-619b80f93368.jpg)
![foot1](https://cloud.githubusercontent.com/assets/19666316/24483876/ea98c802-14c8-11e7-883e-9947d782c7c5.jpg)
![chairright](https://cloud.githubusercontent.com/assets/19666316/24483881/ea9f104a-14c8-11e7-9c4f-f57d678619ec.jpg)
![chairr2](https://cloud.githubusercontent.com/assets/19666316/24483880/ea9d573c-14c8-11e7-9e54-12acfb258696.jpg)
![chairr](https://cloud.githubusercontent.com/assets/19666316/24483882/ea9f904c-14c8-11e7-9c1c-89ca17e13862.jpg)
![chairl2](https://cloud.githubusercontent.com/assets/19666316/24483883/eaa02228-14c8-11e7-9cb6-02e95807a129.jpg)
![chairl1](https://cloud.githubusercontent.com/assets/19666316/24483884/eaa203fe-14c8-11e7-8743-be23963239f9.jpg)
![chairback3](https://cloud.githubusercontent.com/assets/19666316/24483885/eaa2fc1e-14c8-11e7-84a2-99422833b35b.jpg)
![chairback2](https://cloud.githubusercontent.com/assets/19666316/24483886/eaa61b6a-14c8-11e7-9eaa-1ba10ba20487.jpg)
![chairback1](https://cloud.githubusercontent.com/assets/19666316/24483887/eaa9a546-14c8-11e7-90a7-e56a52bb00c4.jpg)

**Comment by sarah-widder** [comment]
![tableassemblylight](https://cloud.githubusercontent.com/assets/19666316/24484779/03c3142c-14ce-11e7-9503-d977d94b5486.jpg)
![shelfassemblylight](https://cloud.githubusercontent.com/assets/19666316/24484780/03c5331a-14ce-11e7-9919-e9aa1618baa2.jpg)
![consoleassemblylight](https://cloud.githubusercontent.com/assets/19666316/24484782/03c8d894-14ce-11e7-9cef-2ec711f4c274.jpg)
![chairassemblylight](https://cloud.githubusercontent.com/assets/19666316/24484781/03c8e1b8-14ce-11e7-99cf-7ef95a633057.jpg)

**Comment by szeylikm** [comment]
<img width="641" alt="screen shot 2017-04-11 at 1 33 13 pm" src="https://cloud.githubusercontent.com/assets/12373812/24922344/f9500516-1ebb-11e7-9aaf-9c50469bd2c8.png">
