### ISSUE TITLE
[gh-pages] Menu toggle button not visible (on mobile)

### ISSUE THREAD

**Issue by omangin** [ScazLab/HRC-model-set#5]
Currently on mobile (or narrow screens), the button to toggle the menu (top right) is not visible.
We could change it by adding some content to the button like the character: ☰ (`&#9776;`).
![2017-03-30-111333_1064x762_scrot](https://cloud.githubusercontent.com/assets/1171989/24512030/6de3bcfe-153b-11e7-978d-2ed7c9467e6e.png)

**Comment by alecive** [comment]
I think that there was something like that in the beginnign, but the image was lost down the road.
